# Generated by Django 5.1.3 on 2024-12-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='armodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistid', models.CharField(blank=True, max_length=100, null=True)),
                ('modelname', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='arimage')),
            ],
        ),
    ]
