# Generated by Django 5.1.3 on 2024-12-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notoificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('ARTISTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artisttable')),
            ],
        ),
        migrations.AddField(
            model_name='artisttable',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable'),
        ),
        migrations.CreateModel(
            name='ModelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ARTISTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artisttable')),
            ],
        ),
        migrations.CreateModel(
            name='paymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentmethod', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookingtable')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='feedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='complaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('reply', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable'),
        ),
    ]
