# Generated by Django 5.1.3 on 2024-12-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='ARTISTID',
            new_name='ARTIST',
        ),
        migrations.RenameField(
            model_name='bookingtable',
            old_name='USERID',
            new_name='USER',
        ),
    ]
